databases:
  - name: qma-db
    databaseName: quantity_measurement
    user: postgres
    plan: free

services:
  # 1. Service Registry (Eureka)
  - type: web
    name: qma-registry
    env: docker
    dockerContext: .
    dockerfilePath: QMA-Registry/Dockerfile
    plan: free
    healthCheckPath: /actuator/health

  # 2. Auth Service
  - type: web
    name: QuantityMeasurementApp-Auth
    env: docker
    dockerContext: .
    dockerfilePath: QMA-Auth/Dockerfile
    plan: free
    envVars:
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        fromService:
          name: qma-registry
          type: web
          property: host
          suffix: /eureka/
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: qma-db
          property: connectionString
      - key: QMA_JWT_SECRET
        generateValue: true

  # 3. Quantity Service
  - type: web
    name: qma-service
    env: docker
    dockerContext: .
    dockerfilePath: QMA-Service/Dockerfile
    plan: free
    envVars:
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        fromService:
          name: qma-registry
          type: web
          property: host
          suffix: /eureka/
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: qma-db
          property: connectionString

  # 4. API Gateway
  - type: web
    name: qma-api
    env: docker
    dockerContext: .
    dockerfilePath: QMA-API/Dockerfile
    plan: free
    envVars:
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        fromService:
          name: qma-registry
          type: web
          property: host
          suffix: /eureka/

staticSites:
  # 5. Frontend (React)
  - name: QuantityMeasurementApp
    rootDir: QMA-Client
    buildCommand: npm install && npm run build
    publishDir: dist
