services:
  # 1. Service Registry (Eureka)
  - type: web
    name: qma-registry
    env: docker
    dockerContext: .
    dockerfilePath: QMA-Registry/Dockerfile
    plan: free
    healthCheckPath: /actuator/health

  # 2. Auth Service
  - type: web
    name: QuantityMeasurementApp-Auth
    env: docker
    dockerContext: QMA-Auth
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: https://qma-eureka-kuee.onrender.com/eureka/
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://qma-3c9ee81a-qma-06052026.i.aivencloud.com:22985/defaultdb?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: avnadmin
      - key: SPRING_DATASOURCE_PASSWORD
        value: AVNS_wnVjkTVNyu3Igttd7RT
      - key: QMA_JWT_SECRET
        value: b1f5e6d7c8a9b0c1d2e3f405162738495a6b7c8d9e0f1a2b3c4d5e6f708192a3b4c5d6e7f8091a2b3c4d5e6f708192a3b
      - key: QMA_OAUTH2_REDIRECT_URI
        value: https://quantitymeasurementapp-p0gz.onrender.com/oauth/callback
      - key: QMA_FRONTEND_ORIGIN
        value: https://quantitymeasurementapp-p0gz.onrender.com
      - key: QMA_CORS_ALLOWED_ORIGINS
        value: https://quantitymeasurementapp-p0gz.onrender.com
      - key: QMA_GOOGLE_AUTH_REDIRECT_URI
        value: https://quantitymeasurementapp-auth-9cyo.onrender.com/login/oauth2/code/google
      - key: GOOGLE_CLIENT_ID
        value: 332652104232-bjke91gs5g6tj9357gibsu95hpa6h5rn.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        value: 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

  # 3. Quantity Service
  - type: web
    name: qma-service
    env: docker
    dockerContext: QMA-Service
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: https://qma-eureka-kuee.onrender.com/eureka/
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://qma-3c9ee81a-qma-06052026.i.aivencloud.com:22985/defaultdb?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: avnadmin
      - key: SPRING_DATASOURCE_PASSWORD
        value: AVNS_wnVjkTVNyu3Igttd7RT

  # 4. API Gateway
  - type: web
    name: qma-api
    env: docker
    dockerContext: QMA-API
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: https://qma-eureka-kuee.onrender.com/eureka/

  # 5. Frontend (React)
  - type: web
    name: QuantityMeasurementApp
    env: static
    rootDir: QMA-Client
    buildCommand: npm install && npm run build
    publishDir: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html