spring.application.name=qma-api-gateway
server.port=4000
server.forward-headers-strategy=framework
spring.cloud.gateway.server.webflux.x-forwarded.enabled=true

spring.cloud.gateway.server.webflux.routes[0].id=qma-auth-api
spring.cloud.gateway.server.webflux.routes[0].uri=lb://QMA-AUTH
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/auth/**,/oauth2/**,/login/oauth2/**

spring.cloud.gateway.server.webflux.routes[1].id=qma-user-history-api
spring.cloud.gateway.server.webflux.routes[1].uri=lb://QMA-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/users/me/history
spring.cloud.gateway.server.webflux.routes[1].filters[0]=RewritePath=/api/v1/users/me/history, /api/v1/quantities/me/history

spring.cloud.gateway.server.webflux.routes[2].id=qma-service-api
spring.cloud.gateway.server.webflux.routes[2].uri=lb://QMA-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/quantities/**,/api/v1/health/**

spring.cloud.gateway.server.webflux.routes[3].id=qma-user-api
spring.cloud.gateway.server.webflux.routes[3].uri=lb://QMA-AUTH
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/v1/users/**

spring.cloud.gateway.server.webflux.routes[4].id=qma-auth-openapi
spring.cloud.gateway.server.webflux.routes[4].uri=lb://QMA-AUTH
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api-docs/auth
spring.cloud.gateway.server.webflux.routes[4].filters[0]=RewritePath=/api-docs/auth, /v3/api-docs

spring.cloud.gateway.server.webflux.routes[5].id=qma-service-openapi
spring.cloud.gateway.server.webflux.routes[5].uri=lb://QMA-SERVICE
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api-docs/qma
spring.cloud.gateway.server.webflux.routes[5].filters[0]=RewritePath=/api-docs/qma, /v3/api-docs

# Global CORS configuration
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origin-patterns=http://localhost:5173,http://localhost:3000,http://localhost:8000,http://localhost:4000,http://127.0.0.1:8000,http://127.0.0.1:5173,https://quantitymeasurementapp-p0gz.onrender.com
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].exposed-headers=Authorization,Set-Cookie,X-User-Email
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true
spring.cloud.gateway.globalcors.cors-configurations.[/**].max-age=3600

app.jwt.secret=${QMA_JWT_SECRET:change-me-to-a-long-random-secret-key-at-least-32-bytes}

springdoc.swagger-ui.path=/swagger
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.urls[0].name=QMA Auth API
springdoc.swagger-ui.urls[0].url=/api-docs/auth
springdoc.swagger-ui.urls[1].name=QMA Service API
springdoc.swagger-ui.urls[1].url=/api-docs/qma

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
