spring.application.name=QMA-SERVICE


server.port=6000

# Remote Aiven Database (Commented out)
# spring.datasource.url=${QMA_SERVICE_DB_URL:${QMA_DB_URL:jdbc:postgresql://qma-3c9ee81a-qma-06052026.i.aivencloud.com:22985/defaultdb?sslmode=require}}
# spring.datasource.username=${QMA_SERVICE_DB_USERNAME:${QMA_DB_USERNAME:avnadmin}}
# spring.datasource.password=${QMA_SERVICE_DB_PASSWORD:${QMA_DB_PASSWORD:AVNS_wnVjkTVNyu3Igttd7RT}}
# spring.datasource.driver-class-name=org.postgresql.Driver

# Local Database
spring.datasource.url=jdbc:postgresql://localhost:5432/quantity_measurement
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

app.jwt.secret=${QMA_JWT_SECRET:change-me-to-a-long-random-secret-key-at-least-32-bytes}
app.jwt.expiration-ms=${QMA_JWT_EXPIRATION_MS:3600000}

# Production: https://quantitymeasurementapp-p0gz.onrender.com/oauth/callback
app.oauth2.redirect-uri=${QMA_OAUTH2_REDIRECT_URI:http://localhost:5173/oauth/callback}
# Production: https://quantitymeasurementapp-p0gz.onrender.com
app.oauth2.frontend-origin=${QMA_FRONTEND_ORIGIN:http://localhost:5173,http://localhost:3000}
app.oauth2.google.auth-redirect-uri=${QMA_GOOGLE_AUTH_REDIRECT_URI:http://localhost:4000/login/oauth2/code/google}
 
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.client-id=185197611345-ejn6t5krdp6h51dh7jrbume2557fuuvq.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

logging.level.org.springframework.security=INFO
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

springdoc.api-docs.path=/v3/api-docs
